### PR TITLE
Suppress GCC anonymous struct warning

### PR DESCRIPTION
**Pull request by kevinmoran**
Suppress GCC anonymous struct warning

### CODE REVIEW

**Comment by bvisness** [comment]
Looks good to me, how about you, @StrangeZak?

**Comment by StrangeZak** [comment]
@bvisness Yep, looks fine will merge it in, its stupid C++ compilers do no handle *.h files as C11 in the first place, though.

**Comment by DanielGibson** [comment]
Sorry to spam this old merge request, but this change gives me compiler warnings.

At least GCC 5.4.0 doesn't know about "-Wgnu-anonymous-struct" and thus I get the warning
```
.../HandmadeMath.h:184:9: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
 #pragma GCC diagnostic ignored "-Wgnu-anonymous-struct"
```
So maybe it shouldn't just check `#ifdef __GNUC__` but also the version?
In fact, does that warning even exist in any version of GCC? I only saw it mentioned in clang documentation.

Furthermore, I'd suggest using `#pragma GCC diagnostic push` (before `#pragma GCC diagnostic ignored "-Wgnu-anonymous-struct"` and `#pragma GCC diagnostic pop` (at the end of the file) to make sure that supressing that warning doesn't "leak out" into the users code.

Side-node: If stupid C++ compilers handled *.h as C11 code (instead of C++), tons of software that uses .h for C++ headers would explode, so it's probably better this way ;)

**Comment by StrangeZak** [comment]
Will look into this tonight, and figure it out!

**Pull request merged**
