### PR TITLE
Matrix Multiply SSE

### PR DESCRIPTION
**Pull request by bvisness**
Just making a PR so we have a common place for discussion.

### CODE REVIEW

**Comment by bvisness** [comment]
@StrangeZak I had to tweak the test compilation process so that the SSE `#define`s worked correctly. Everything seems to be in order now.

**Comment by StrangeZak** [comment]
Seems like everything i wanted to be done is done. @bvisness take a look and see if there's anything i should change.

Also, i am worried about the _MM_TRANSPOSE4_PS i added since it is a helper macro. Is it safe to assume all everyone will have this macro?

**Comment by bvisness** [comment]
@StrangeZak I added C versions of the vector equality stuff you added.

If the SSE tests pass in clang and gcc, and it works for you in Visual Studio, then I think it's safe to assume that the macro is widely supported.

**Comment by bvisness** [comment]
I think after this is merged and taken care of, I'm going to revisit #57 and rework our use of `inline`.

**Comment by StrangeZak** [comment]
@bvisness Looks good to me. Shall i go ahead an do the merge ?

**Comment by bvisness** [comment]
Go for it!

**Comment by StrangeZak** [comment]
Done!

**Pull request merged**
